project:
  name: quickstart-chainlinklabs-chainlink-node
  regions:
  # only able to test in region with SSL certificates set up through AWS Certificate Manager with the SSL Certificate ARN
    #- af-south-1
    #- ap-east-1
    #- ap-south-1
    #- ap-northeast-3
    #- ap-northeast-2
    - ap-southeast-1
    #- ap-southeast-2
    #- ap-northeast-1
    #- ca-central-1
    # - cn-north-1
    # - cn-northwest-1
    #- eu-central-1
    #- eu-west-1
    #- eu-west-2
    #- eu-south-1
    #- eu-west-3
    #- eu-north-1
    #- me-south-1
    #- sa-east-1
    #- us-east-1
    #- us-east-2
    #- us-west-1
    #- us-west-2
tests:
  default:
    template: ./templates/quickstart-chainlink-node-entrypoint.template.yaml
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      KeyPairName: override
      ChainlinkNodeGUIPassword:  $[taskcat_genpass_16S]
      NodeWalletPassword:  $[taskcat_genpass_16S]
      DBMasterUserPassword:  $[taskcat_genpass_16S]
      SSLCertificateARN: ''
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      EnableAmazonDevOpsGuru: 'false'
